PROGRAM	=soukoban
OBJS	=soukoban.co
SRCS	=$(OBJS:%.o=%.c)
CC		=gcc
LD		=gcc
CFLAGS	=-g -Wall
LDFLAGS	=-lcurses
VPATH	=../bin/:../bin/obj
BINPATH	=../bin/
OBJPATH	=../bin/obj/

all:$(PROGRAM)

clean:
	rm -rf $(BINPATH)$(PROGRAM)

